### PR TITLE
update phpseclib to 2.0

### PR DESCRIPTION
**Pull request by andreybolonin**
``` sh
2015-09-22 13:38:14 [-][-][-][error][yii\base\ErrorException:2] exception 'yii\base\ErrorException' with message 'unpack(): Type N: not enough input, need 4, have 1' in /data/cporder-2-0/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2826
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'unpack(): Type ...', '/data/cporder-2...', 2826, Array)
#1 /data/cporder-2-0/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2826): unpack('Nlength', '\x00')
#2 /data/cporder-2-0/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2771): Net_SSH2->_filter('P\x00\x00\x00\x17hostkeys-0...')
#3 /data/cporder-2-0/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2974): Net_SSH2->_get_binary_packet()
#4 /data/cporder-2-0/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(441): Net_SSH2->_get_channel_packet(256)
#5 /data/cporder-2-0/vendor/league/flysystem-sftp/src/SftpAdapter.php(126): Net_SFTP->login('CentralPoint', 'VoOe8TVK4QW5mB9...')
#6 /data/cporder-2-0/vendor/league/flysystem-sftp/src/SftpAdapter.php(115): League\Flysystem\Sftp\SftpAdapter->login()
#7 /data/cporder-2-0/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(563): League\Flysystem\Sftp\SftpAdapter->connect()
#8 /data/cporder-2-0/vendor/league/flysystem-sftp/src/SftpAdapter.php(194): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
#9 /data/cporder-2-0/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(317): League\Flysystem\Sftp\SftpAdapter->listDirectoryContents('download', false)
#10 /data/cporder-2-0/vendor/league/flysystem/src/Filesystem.php(268): League\Flysystem\Adapter\AbstractFtpAdapter->listContents('download', false)
#11 /data/cporder-2-0/vendor/league/flysystem/src/Plugin/ListFiles.php(27): League\Flysystem\Filesystem->listContents('download', false)
#12 [internal function]: League\Flysystem\Plugin\ListFiles->handle('download')
#13 /data/cporder-2-0/vendor/league/flysystem/src/Plugin/PluggableTrait.php(67): call_user_func_array(Array, Array)
#14 /data/cporder-2-0/vendor/league/flysystem/src/Plugin/PluggableTrait.php(83): League\Flysystem\Filesystem->invokePlugin('listFiles', Array, Object(League\Flysystem\Filesystem))
#15 /data/cporder-2-0/components/Transports/TransportSFTP.php(71): League\Flysystem\Filesystem->__call('listFiles', Array)
#16 /data/cporder-2-0/components/Transports/TransportSFTP.php(71): League\Flysystem\Filesystem->listFiles('download')
#17 /data/cporder-2-0/commands/ServiceController.php(740): app\components\Transports\TransportSFTP->get()
#18 [internal function]: app\commands\ServiceController->actionTieGetOrd()
#19 /data/cporder-2-0/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#20 /data/cporder-2-0/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#21 /data/cporder-2-0/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('tie-get-ord', Array)
#22 /data/cporder-2-0/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('tie-get-ord', Array)
#23 /data/cporder-2-0/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('service/tie-get...', Array)
#24 /data/cporder-2-0/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('service/tie-get...', Array)
#25 /data/cporder-2-0/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#26 /data/cporder-2-0/yii(15): yii\base\Application->run()
#27 {main}
```

https://github.com/phpseclib/phpseclib/issues/669 fixed in 2.x.x version.

### CODE REVIEW

**Comment by frankdejonge** [comment]
@pilotftzi I'm pretty sure something is going wrong, changing the package name?

**Comment by andreybolonin** [comment]
Yep, sorry :)

Package is need to use immediately.

You will be able to merge today?

**Comment by andreybolonin** [comment]
@frankdejonge ping

**Comment by soee** [comment]
@frankdejonge also ping. Through this #12 and #14 could be closed.

**Comment by gabriel403** [comment]
@frankdejonge any movement on this?

**Pull request merged**
