### PR TITLE
Replace error suppression, prevent private key disclosure

### PR DESCRIPTION
**Pull request by weshooper**
Fix for https://github.com/thephpleague/flysystem-sftp/issues/18

### CODE REVIEW

**Comment by weshooper** [comment]
Travis CI is failing due to setup issue there:

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

**Comment by weshooper** [comment]
@frankdejonge is there anything I can do to help this along?

**Comment by frankdejonge** [comment]
@weshooper tagged as 1.0.14

**Comment by weshooper** [comment]
Thanks @frankdejonge 😄

**Pull request merged**
