### PR TITLE
Throw an Exception if can't connect to check Host Fingerprint

### PR DESCRIPTION
**Pull request by liamkeily**
If this adapter can't connect to the server it still assumes it has the public key and tries to verify it causing the following error: `ErrorException (Undefined offset: 1) flysystem-sftp/src/SftpAdapter.php:217`

This change provides a more useful error

### CODE REVIEW

**Comment by liamkeily** [comment]
Weird test failure here which i noticed also happens in another PR: https://travis-ci.org/thephpleague/flysystem-sftp/jobs/447018564

**Comment by frankdejonge** [comment]
@liamkeily if you rebase on master these errors are gone.

**Comment by liamkeily** [comment]
@frankdejonge Thanks this is passing now, any thoughts?

**Review by frankdejonge — APPROVED** [review]

**Comment by liamkeily** [comment]
@frankdejonge can this be merged?

**Comment by frankdejonge** [comment]
1.0.18 should be out any minute now

**Pull request merged**
