### PR TITLE
Update SftpAdapter.php

### PR DESCRIPTION
**Pull request by intrepido**
Fixing bug

### CODE REVIEW

**Comment by frankdejonge** [comment]
@intrepido what bug is this fixing?

**Comment by intrepido** [comment]
When trying to get the listing of a directories with subdirectories some directories don't have the property type, and I'm receiving this error:

`PHP Notice:  Undefined index`

**Comment by intrepido** [comment]
Please, notify me if you will take any action about the error soon, because I want to use this package in my project. I really like this package and I wouldn't like to change it and to use another one. Thank you.

**Comment by frankdejonge** [comment]
@intrepido tagged as 1.0.13

**Pull request merged**
