### PR TITLE
fix(GOTO): remove goto statement

### PR DESCRIPTION
**Pull request by andrzejd-pl**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@andrzejd-pl Hi, is there an actual bug you're fixing here or is this simple rewriting to not use goto?

**Comment by andrzejd-pl** [comment]
simple rewriting to not use goto

**Comment by frankdejonge** [comment]
Thanks, but no thanks.

**Comment by andrzejd-pl** [comment]
so, why you use `goto`?

**Comment by frankdejonge** [comment]
It works, in these cases where a some work is a linear set of operations, with steps that can be skipped I think a goto is quite elegant and more readable than nested if statements.

**Comment by andrzejd-pl** [comment]
Using `goto` isn't pretty. It's a dangerous statement (All software developers tell: "You are crazy? This `goto`!" 😉  ). In my opinion, better use 'if' statement - clarify the algorithm.
If you want to have an elegant code, I'll improve my code to scheme:
```php
if (condition) {
    throw new XyzException(...);
}

//do something
}
```

**Pull request closed without merging**
