### PR TITLE
#98: SftpAdapter tries to create a missing directory on rename

### PR DESCRIPTION
**Pull request by proggeler**

### CODE REVIEW

**Comment by frankdejonge** [comment]
@proggeler instead of modifying the test case, can you create an additional test with a move from a path like "nest/filename.txt" to "new-directory/newname.txt"?

**Comment by proggeler** [comment]
@frankdejonge I think you want to check the existing directory does not call createDir too. (that's why I editted this one)
I've also added one to check the createDIr is called when the directory is missing. 
Do you want another where both the dir is missing and the filename is altered?

**Comment by souhail-5** [comment]
Hello :) Any update on this? Can I help you?

**Comment by proggeler** [comment]
@frankdejonge It is some time ago, but maybe you can check this again?

**Comment by proggeler** [comment]
obsolete in the new version

**Pull request closed without merging**
